### DISCUSSION TITLE
YMU - YimMenuUpdater (Downloader/Updater/Injector)

### DISCUSSION THREAD

**Discussion by NiiV3AU** [YimMenu/YimMenu#3210] [General]
Hey guys 👋🏻,
First of, YimMenu is no doubt a real gem in the gta modding scene and I just uploaded [**YMU**](https://github.com/NiiV3AU/YMU), its a small Python GUI which can Download the latest version of YimMenu and update it. Also you can see the SHA256 of your downloaded (local) file and compare it with the GitHub Build SHA256. Im a rookie dev so please be nice if there are flaws in my code. You can always share your feedback and request features, I try my best to fulfill your requests and to develope robust code.
> I hope its ok to say it here, its not meant to be self advertisement I just like the project and build it for myself and wanted to share if anyone is interested

`Everything I upload is Open Source!`

**Comment by ghost** [comment]
maybe it’s worth making a full-fledged launchpad [like stand did](https://github.com/calamity-inc/Stand-Launchpad).  so that in addition to the update, you can immediately inject and, if possible, add the ability to view commits or changelog

**Reply by maybegreat48** [reply]
See for example [this](https://github.com/infodox/python-dll-injection/blob/master/dll_inject.py) thing

**Reply by NiiV3AU** [reply]
>if possible, add the ability to view commits or changelog

You mean the changelog of the YimMenu? I will look into it.

**Reply by NiiV3AU** [reply]
> See for example [this](https://github.com/infodox/python-dll-injection/blob/master/dll_inject.py) thing

Thanks

**Reply by ghost** [reply]
> > if possible, add the ability to view commits or changelog
> 
> You mean the changelog of the YimMenu? I will look into it.

I meant just adding the ability to view [the list of changes](https://github.com/YimMenu/YimMenu/commits/master/) or just [this](https://yim.gta.menu/changelog.html). Apparently, the main requirement is that GitHub Actions must compile the project in such a way that no one has any questions about the presence of viruses.

**Comment by Deadlineem** [comment]
I personally just created a batch file for downloading/updating YimMenu.  
https://github.com/Deadlineem/Extras-Addon-for-YimMenu/blob/main/update.bat

It makes life a whole lot easier for sure, a launchpad/dll injector would be nice but it would have to be open source like 

https://github.com/fligger/FateInjector -- Which also does not flag on windows defender or any other virus scanners I've used so it would be great to use as a base for a launchpad imo.

**Comment by NiiV3AU** [comment]
Thanks for the input guys, Im going to take a closer look to the injection aspect. I will update it as soon as I can.

**Comment by xesdoog** [comment]
This is neat I love it! if you want you can collaborate with @Deadlineem and [USBMenus](https://github.com/USBMenus), they wrote something similar in C# and it was very nice! I think it also had a dll injector although I'm not sure, I haven't been around in a little while. 
Having a launch pad would be a great step towards making this awesome project even more powerful and we could probably throw a little something extra for Lua scripts too.

**Reply by Rxann** [reply]
Stand also writes theirs in C#

**Reply by xesdoog** [reply]
Hey Ryan how have you been? You still rocking that Drake profile picture? 🤣

> Stand also writes theirs in C# 

Yes but I think this is simpler. The injection part is literally 5 or 6 lines of code and it just works. This can be converted to use ImGui as well with little to no effort.. Or maybe I'm just saying this because I don't like the C family lol idk but I like the idea of having something like this regardless of the language.

**Reply by ghost** [reply]
> Hey Ryan how have you been? You still rocking that Drake profile picture? 🤣
> 
> > Stand also writes theirs in C#
> 
> Yes but I think this is simpler. The injection part is literally 5 or 6 lines of code and it just works. This can be converted to use ImGui as well with little to no effort.. Or maybe I'm just saying this because I don't like the C family lol idk but I like the idea of having something like this regardless of the language.

Can you recompile this using GitHub Actions in .exe? Not everyone has Python installed on their computer, but we focus on ordinary users

**Reply by xesdoog** [reply]
Yes we can. I would need permission from @NiiV3AU to do it myself but we can simply use [PyInstaller Action](https://github.com/marketplace/actions/pyinstaller-action)

**Reply by NiiV3AU** [reply]
Guys Im too stupid to figure this action out!? What do I need to paste in the action.yml file? My inputs for pyinstaller are: `pyinstaller --noconfirm --onefile --windowed  "YMU/ymu.py"`. If you could help me out I will update my repo asap

**Reply by Rxann** [reply]
> Hey Ryan how have you been? You still rocking that Drake profile picture? 🤣
> 
> > Stand also writes theirs in C# 
> 
> Yes but I think this is simpler. The injection part is literally 5 or 6 lines of code and it just works. This can be converted to use ImGui as well with little to no effort.. Or maybe I'm just saying this because I don't like the C family lol idk but I like the idea of having something like this regardless of the language.

Hi Xes and yes I am. I only like c and c++. Mostly the ladder half. It is still true that it is very easy to do in c#.

**Reply by xesdoog** [reply]
Create a blank workflow file and paste this inside it:
You will either need to upload an icon file to the repo and name it ymu.ico or remove this entry from the pyinstaller command: 
`--icon=ymu.ico`
```yaml
# This workflow will install Python dependencies, run tests, build an executable then upload it to github releases

name: YMU Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pyinstaller
        pip install -r requirements.txt
    - name: flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: create binary
      run: |
        pyinstaller --noconfirm --onefile --windowed --noconsole --icon=ymu.ico "ymu.py"
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: binary
        path: |
          dist\ymu.exe
    - name: Generate Build Info
      id: var
      run: |
        echo "full_sha=$(git rev-parse HEAD)" >> $env:GITHUB_OUTPUT
        echo "short_sha=$(git rev-parse --short HEAD)" >> $env:GITHUB_OUTPUT

  create_release:
  
    runs-on: ubuntu-latest
    name: Create Release
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Delete Existing Release
      id: delete_ex_release
      uses: actions/github-script@v6
      with:
        script: |
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const tag = "release";
      
            // List all releases and find the release by tag
            const releases = await github.rest.repos.listReleases({
              owner: owner,
              repo: repo,
            });
      
            const release = releases.data.find(release => release.tag_name === tag);
      
            // Check if the release exists and delete it
            if (release) {
              await github.rest.repos.deleteRelease({
                owner: owner,
                repo: repo,
                release_id: release.id,
              });
              console.log(`Deleted release with ID ${release.id}`);
            } else {
              console.log("No existing release to delete");
            }
      
            // Delete the tag
            try {
              await github.rest.git.deleteRef({
                owner: owner,
                repo: repo,
                ref: `tags/${tag}`,
              });
              console.log(`Deleted tag ${tag}`);
            } catch (error) {
              console.error(`Error deleting tag: ${error.message}`);
            }

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: binary

    - name: Echo build sha256
      id: build_sha
      run: |
        sha256sum ymu.exe > sha256.checksum
        echo "build_sha=$(cat sha256.checksum)" >> $GITHUB_OUTPUT
        cat sha256.checksum
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: YMU
        tag_name: release
        body: |
            **This release has been built by Github Actions**
            [Link to build](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

        files: |
          ymu.exe
```

Keep in mind that this will automatically run and create a new release with every commit to the main branch. 

PS: I stole the release upload part from YimMenu's workflow 😂
